project_id = "jeqsesqlkjklhyvszpgg"

[functions.admin-action]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.check-rank-expiry]
verify_jwt = false
